// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// PostHandler is an autogenerated mock type for the PostHandler type
type PostHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields:
func (_m *PostHandler) Create() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// Update provides a mock function with given fields:
func (_m *PostHandler) Update() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewPostHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostHandler creates a new instance of PostHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostHandler(t mockConstructorTestingTNewPostHandler) *PostHandler {
	mock := &PostHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
