// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// PostData is an autogenerated mock type for the PostData type
type PostData struct {
	mock.Mock
}

// CreatePostData provides a mock function with given fields: newpost
func (_m *PostData) CreatePostData(newpost domain.Post) domain.Post {
	ret := _m.Called(newpost)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(domain.Post) domain.Post); ok {
		r0 = rf(newpost)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	return r0
}

// UpdatePostData provides a mock function with given fields: newpost
func (_m *PostData) UpdatePostData(newpost domain.Post) domain.Post {
	ret := _m.Called(newpost)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(domain.Post) domain.Post); ok {
		r0 = rf(newpost)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	return r0
}

type mockConstructorTestingTNewPostData interface {
	mock.TestingT
	Cleanup(func())
}

// NewPostData creates a new instance of PostData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostData(t mockConstructorTestingTNewPostData) *PostData {
	mock := &PostData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
