// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "backend/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: userid
func (_m *UserUseCase) DeleteUser(userid int) (bool, error) {
	ret := _m.Called(userid)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(userid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: newuser, cost
func (_m *UserUseCase) RegisterUser(newuser domain.User, cost int) int {
	ret := _m.Called(newuser, cost)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.User, int) int); ok {
		r0 = rf(newuser, cost)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// SearchUser provides a mock function with given fields: username
func (_m *UserUseCase) SearchUser(username string) (domain.User, error) {
	ret := _m.Called(username)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(string) domain.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: newuser, userid, cost
func (_m *UserUseCase) UpdateUser(newuser domain.User, userid int, cost int) int {
	ret := _m.Called(newuser, userid, cost)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.User, int, int) int); ok {
		r0 = rf(newuser, userid, cost)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewUserUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUseCase(t mockConstructorTestingTNewUserUseCase) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
